name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible-ping.yml'
 
jobs:
  ansible-ping:
    runs-on: macbook-seb
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: python -m pip install ansible

      - name: Execute Ping Playbook
        run: ansible-playbook ansible/ping.yml -i ansible/inventory.ini
